// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfU0W0vOrPD54DacLnxzPW_h4D0GQNqjA',
    appId: '1:758854886821:android:7edf773e124b007d71744c',
    messagingSenderId: '758854886821',
    projectId: 'car-rental-app-3a52c',
    storageBucket: 'car-rental-app-3a52c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Scwv401v963zwfZxy6gePQr0T1XcC0g',
    appId: '1:758854886821:ios:5a6565caaf2f0fc871744c',
    messagingSenderId: '758854886821',
    projectId: 'car-rental-app-3a52c',
    storageBucket: 'car-rental-app-3a52c.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYn0Du-819aBeR8UhGjb4xFy6xBYPc5Fk',
    appId: '1:758854886821:web:f0a96eb7354a1b2771744c',
    messagingSenderId: '758854886821',
    projectId: 'car-rental-app-3a52c',
    authDomain: 'car-rental-app-3a52c.firebaseapp.com',
    storageBucket: 'car-rental-app-3a52c.firebasestorage.app',
    measurementId: 'G-V4TZZ43LWX',
  );

}